### ISSUE TITLE
Is not working in the Top Gear (E) [!].smc

### ISSUE THREAD

**Issue by leomarx71** [GameHackFan/tge#1]
Hello @GameHackFan is not working when I tried to apply more laps in the first track. The process is:
1 - Select Track and Quantity
2 - Load Rom
3 - Clone Rom
4 - Download Rom ?

Do you have a ROM that is working ? Can you attach here to see and test ? Can I apply to modified ROM ?

Additionally:
I tried to read your code I could not understand the logic that you are applying in the getLapBytes and how and what codes you are modifying in the ROM, is possible to put a new field and expand the code to implement game genie codes ? Like 10 Laps but with infinite fuel or infinite nitro ? I am really fan and would like to play in this scenarios :)
https://etherealgames.com/snes/t/top-gear/game-genie-codes/

**Comment by GameHackFan** [comment]
Hi, I believe I tested it on an European version previously and it worked, but I might be wrong because I don't remember, so I need to check it, but the process would be Load ROM and Clone ROM first (for all my editors, always do that first), then you select the track you want to edit, change the value, then you generate ROM.

About the game genie codes, I would have to look at them to see what can be done.

About the getLapBytes, I made this editor a long time ago, so I might not remember 100%, but I believe it is bytes near the bytes of the lap, so it just returns those bytes, then another method find the index of these bytes inside the ROM and use them as a guide to find the index of the bytes of the laps.

**Comment by GameHackFan** [comment]
Well, I tested today and it works perfectly fine with the European version.

About a hacked ROM, it might work if the hack didn't change the bytes near the lap data, as I explained, they are used to find out where the bytes of the laps are, so if the bytes used as guide to find the lap bytes are not changed, the editor will work.

Just a warning, since the SNES ROMs are just a single file, avoid loading compressed files, load only .smc or .sfc files and it must work for sure.

Please try again and tell me what was the result so I can close this issue.

**Comment by leomarx71** [comment]
Hey I follow you procedure it works perfectly selecting the name and number of laps after upload and clone... 
You may create a guide in md file or just change the HTML page, then people will realize the order of tasks.
I tested in another hacked ROM and worked ok also. Is ok and you can close the issue. Thanks a lot.

If you have space in your schedules to create a custom ROM for me in a freelancer, just let me know by discord LeomarxGames#2111 to discuss details. Thanks and see you.

**Comment by GameHackFan** [comment]
I don't know SNES assembly that well.
